openapi: 3.0.0

servers:
  - url: http://{host}:{port}/orion/v0.1
    variables:
      host:
        default: localhost
        description: Server domain
      port:
        default: "8080"
        description: Server port

info:
  description: This is the RESTful APIs of the ORION Distributed Computing Framework
  version: "1.0.0"
  contact:
    email: tharindu.bandara.edu@gmail.com
    name: Tharindu Bandara
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  title: ORION RESTful APIs
tags:
  - name: Client Admin
    description: Secured for client admin calls
paths:
  /task-limits:
    get:
      tags:
        - Client Admin
      summary: provide resource limits of a worker
      operationId: getTaskLimitations
      description: |
        You can obtain resource limitations of a worker such as RAM. Based on that, the submitting job can be planned.
      responses:
        '200':
          description: task resources limits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskLimits'
        '404':
          description: Could not find limitations
components:
  schemas:
    TaskLimits:
      type: object
      properties:
        memory:
          type: number
          example: 2
          description: Memory in GBs
        additionalProperties:
          type: array
          items:
            $ref: '#/components/schemas/Property'
          description: Additional properties may sent by the server.
    Property:
      type: object
      properties:
        key:
          type: string
          example: storage
          description: Any key value of the property.
        value:
          type: string
          example: 5
          description: Value of the property.